---
title: rockboxfr
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: RockboxFR
description:  RockboxFR page en français dédié au Firmware Rockbox pour les lecteur de musique gratuit.
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
twitter_username: Blindhelp38
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: BlindHelp
  instagram: 
  linkedin: 
  pinterest: 
  rss: https://blindhelp.github.io/rockboxfr/feed.xml
  twitter: 
  stackoverflow: 
  youtube: 
  googleplus: 
disqus: 
google_analytics: 
url: 
baseurl: 'https://blindhelp.github.io/rockboxfr'
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile.lock
- LICENSE
- README.md
- CNAME
authors:
  RockboxFR:
    name: RockboxFR
    display_name: RockboxFR
    web: https://blindhelp.github.io/rockboxfr
issues_repo: BlindHelp/rockboxfr